console.log("GET ELEMENT BY ID: ");
let h = document.getElementById("thirdHeading");
h.style.backgroundColor = "salmon";
h.style.color = "white";
// console.log(h);
// document.getElementById("thirdHeading").style;
// document.getElementById("thirdHeading").style.color = "yellow";
h.style.textAlign = "center";
let h1 = document.getElementById("firstHeading");
h1.innerText = "Heading 1 change by js";
